### PR TITLE
add newline to file after adding header

### LINKED ISSUE #153: addheader removes newline at end of file
Since it's generally undesirable to *remove* anything when adding a license header and also clutters git diffs, I'd consider this a bug.

#Reproduction

* install reuse 0.8.0 via pip3
* Apply to bunch of C++ files ending in a newline: `reuse addheader --license "AGPL-3.0-or-later" FILENAMES.?pp`
* git diff excerpt:

```diff
diff --git a/include/FILENAME.hpp b/include/FILENAME.hpp
index 8afac27..a2f27de 100644
--- a/include/FILENAME.hpp
+++ b/include/FILENAME.hpp
@@ -0,0 +1,2 @@
+// SPDX-License-Identifier: AGPL-3.0-or-later
+
@@ -7 +9 @@ //some code here
-#endif
+#endif
\ No newline at end of file
```

#Expected Result

only the header being added, no other source code changes

### PR DESCRIPTION
**Pull request by mxmehl**
Not quite elegant but does the trick for me 

Fixes #153

### CODE REVIEW

**Comment by mxmehl** [comment]
Not sure why the tests fail here, same on master when I run `py.test`.

**Comment by carmenbianca** [comment]
It's because master was very briefly broken with a pylint test. If you merge master, or refactor onto master, it should pass.

**Comment by carmenbianca** [comment]
As an aside: I want to add a test case for this when I have time.

**Comment by mxmehl** [comment]
Ah ok. Still some fails.

Feel free to merge if you think that's something to ignore :)

**Comment by carmenbianca** [comment]
The new fails were introduced by your PR ;) I'll take a look at this soon-ish.

**Comment by carmenbianca** [comment]
Applied a different fix in #164 

Required patching of some tests, which was annoying, but all well and good.

**Pull request closed without merging**
