### PR TITLE
Release 0.8.1

### PR DESCRIPTION
**Pull request by carmenbianca**
Cherry-picked some commits to create a new patch release.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Can't release until later because I don't have my GPG key with me.

**Comment by carmenbianca** [comment]
Made release on PyPI. Need to merge this PR to sync up the repo. Will do that after the weekend.

**Comment by mxmehl** [comment]
You surely have it on your list already, but just to be sure: please create an according tag to also release it for Docker and the several distributions :)

**Comment by carmenbianca** [comment]
Oops. I had pushed the tags to the wrong repo. Pushed them now.

**Comment by mxmehl** [comment]
Ah thanks! I just updated the API worker server, AUR package will follow on Tuesday when I have fast internet again to test

**Pull request merged**
