### PR TITLE
ressources: update to 3.10-16-gd252819 

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
Anything blocks this?

**Comment by mxmehl** [comment]
Sorry, this got lost from our radar.

May I ask you to update the files in your PR to the latest revision? https://github.com/spdx/license-list-data/tree/master/json

**Comment by aparcar** [comment]
Done

**Comment by mxmehl** [comment]
Thanks a bunch!

**Pull request merged**
