### PR TITLE
Add init logic

### PR DESCRIPTION
**Pull request by carmenbianca**

### CODE REVIEW

**Comment by carmenbianca** [comment]
Output:

```
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $ tree                                                                                                                                                 
.

0 directories, 0 files
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $ reuse init                                                                                                                                           
Initializing project for REUSE.

What license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.
GPL-3.0-or-later

What other license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.
CC0-1.0

What other license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.
wrong-license

'wrong-license' is not a valid SPDX License Identifier

What other license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.


What is the name of the project?
Example

What is the internet address of the project?
https://example.com

What is the name of the maintainer?
Jane Doe

What is the e-mail address of the maintainer?
jane@example.com

(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $ tree -a                                                                                                                                              
.
├── LICENSES
│   ├── CC0-1.0.txt
│   └── GPL-3.0-or-later.txt
└── .reuse
    └── dep5

2 directories, 3 files
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $ head LICENSES/CC0-1.0.txt                                                                                                                            
Creative Commons Legal Code

CC0 1.0 Universal CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES
NOT PROVIDE LEGAL SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE
AN ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS INFORMATION
ON AN "AS-IS" BASIS. CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE USE
OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED HEREUNDER, AND DISCLAIMS
LIABILITY FOR DAMAGES RESULTING FROM THE USE OF THIS DOCUMENT OR THE INFORMATION
OR WORKS PROVIDED HEREUNDER.

(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $ cat .reuse/dep5                                                                                                                                      
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: Example
Upstream-Contact: Jane Doe <jane@example.com>
Source: https://example.com

# Files: src/*
# Copyright: $YEAR $NAME <$CONTACT>
# License: ...
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/tmp $   
```

**Comment by carmenbianca** [comment]
Updated the output example. Made it slightly more verbose.

**Comment by mxmehl** [comment]
Nice! Do I understand correctly that dep5 is actually not used for actual files (just a commented out example) but prepared with the necessary information?

**Comment by carmenbianca** [comment]
Correct!

**Comment by mxmehl** [comment]
Perfect, LGTM then :)

**Comment by carmenbianca** [comment]
Waiting to merge this until I figure out how to test this...

**Pull request merged**
