### PR TITLE
Rename `addheader` to `annotate`; add `--no-replace`

### LINKED ISSUE #338: reuse addheader destroys content
Before:

~~~
#!/usr/bin/env sh

# This file must be sourced in sh:
#
#   . `which env_parallel.sh`
#
# after which 'env_parallel' works
#
#
# Copyright (C) 2016-2021 Ole Tange, http://ole.tange.dk and Free
# Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc., 51 Franklin St,
# Fifth Floor, Boston, MA 02110-1301 USA
~~~

Running:
~~~
reuse addheader --copyright="Ole Tange, http://ole.tange.dk and Free Software and Foundation, Inc." --license="GPL-3.0-or-later" /tmp/a.sh
Successfully changed header of /tmp/a.sh
~~~

Results in:
~~~
#!/usr/bin/env sh

# Copyright (C) 2016-2021 Ole Tange, http://ole.tange.dk and Free
# SPDX-FileCopyrightText: 2021 Ole Tange, http://ole.tange.dk and Free Software and Foundation, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
~~~

This destroyed the usage instructions in the comment.

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #338 

# reuse annotate

Plan: Rename `addheader` to `annotate` to reduce confusion.

`annotate` keeps current behaviour: New header if none exists; replace header if exists.

Add `--no-replace` flag to not replace the header.

## Desired behaviour of `--no-replace`

Instead of replacing the first header, add a new header before it. Do NOT pull
SPDX info from the 'old' first header.

```bash
$ reuse annotate --no-replace --license GPL-3.0
```

```python
# This file must be sourced in sh:
#
#   . `which env_parallel.sh`
#
# after which 'env_parallel' works
#
#
# Copyright (C) 2016-2021 Ole Tange, http://ole.tange.dk and Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc., 51 Franklin St,
# Fifth Floor, Boston, MA 02110-1301 USA
```

->

```python
# SPDX-License-Identifier: GPL-3.0

# This file must be sourced in sh:
#
#   . `which env_parallel.sh`
#
# after which 'env_parallel' works
#
#
# Copyright (C) 2016-2021 Ole Tange, http://ole.tange.dk and Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc., 51 Franklin St,
# Fifth Floor, Boston, MA 02110-1301 USA
```

### CODE REVIEW

**Comment by carmenbianca** [comment]
This PR is starting to look good. Ready for review.

**Review by nicorikken — CHANGES_REQUESTED** [review]
Great!! The string hussling took some double checking but seems all good. I would think a test for addheader and the shebangs wouldn't hurt. What do you think?

**Comment by mxmehl** [comment]
Cool, thanks for working on this! As Nico, I'd love to see some tests.

Also, when addheader is gone, I believe some documentation has to be updated as well, right? I'm thinking of the tool steps in the tutorial as well as the video that we offer on the README.

**Comment by carmenbianca** [comment]
Wrote tests. Ready for re-review.

**Review by nicorikken — APPROVED** [review]
Wow what a clean commit list, easy to review 🤩 Good now with the tests. This will be a major win for reuse-tool users.

**Comment by linozen** [comment]
Yes! Thank you so much @carmenbianca :tada:. This will make REUSE's UX much more straightforward.

**Comment by carmenbianca** [comment]
Change log entry is missing.

**Comment by nicorikken** [comment]
@carmenbianca we can add it to the changelog now or do that at release-time.

**Comment by carmenbianca** [comment]
We should add it now. If we delay to release time, we might miss it. At release time I generally just clean up the change log.


I'll do this when I have time.

**Pull request merged**
