### PR TITLE
Deal with extensionless licenses in LICENSES/

### LINKED ISSUE #87: Lint error: Multiple licenses resolve to LGPL-2
I tried to lint the Linux kernel today and received a fatal error, see below:

Git: `git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
Branch: `master`
Commit: `089cf7f6ecb266b6a4164919a2e69bd2f938374a`

This error is rather new, with 0.4.0, linting Linux didn't throw an error.

```
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/Apache-2.0, resolving to Apache-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/CDDL-1.0, resolving to CDDL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/MPL-1.1, resolving to MPL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/exceptions/GCC-exception-2.0, resolving to GCC-exception-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/GPL-2.0, resolving to GPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.0, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.1, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - CRITICAL - LGPL-2 is the SPDX License Identifier of both LICENSES/preferred/LGPL-2.1 and LICENSES/preferred/LGPL-2.0
Traceback (most recent call last):
  File "/usr/bin/reuse", line 11, in <module>
    load_entry_point('fsfe-reuse==0.5.0', 'console_scripts', 'reuse')()
  File "/usr/lib/python3.7/site-packages/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/usr/lib/python3.7/site-packages/reuse/lint.py", line 255, in run
    project = create_project()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 297, in create_project
    return Project(root)
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 63, in __init__
    self.licenses = self._licenses()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 277, in _licenses
    "Multiple licenses resolve to {}".format(identifier)
RuntimeError: Multiple licenses resolve to LGPL-2
```

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #87

Does the following things:

- If a file `LICENSES/GPL-3.0-or-later` is recognised where `GPL-3.0-or-later` is any valid SPDX License Identifier without file extension, then that license is still recognised.

- The user is given a warning in the above scenario.

- The linter does not pass if any such extensionless licenses are found.

This is an improvement from the simple crash documented in #87.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Document this in usage.rst.

**Comment by mxmehl** [comment]
Unfortunately doesn't solve the problem with Linux. Can you confirm or am I doing something wrong?

```
reuse.project - WARNING - LICENSES/dual/Apache-2.0 does not have a file extension
reuse.project - WARNING - LICENSES/dual/CDDL-1.0 does not have a file extension
reuse.project - WARNING - LICENSES/dual/MPL-1.1 does not have a file extension
reuse.project - WARNING - LICENSES/exceptions/GCC-exception-2.0 does not have a file extension
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/GPL-2.0, resolving to GPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.0, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.1, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - CRITICAL - LGPL-2 is the SPDX License Identifier of both LICENSES/preferred/LGPL-2.1 and LICENSES/preferred/LGPL-2.0
Traceback (most recent call last):
  File "/usr/bin/reuse", line 11, in <module>
    load_entry_point('fsfe-reuse==0.5.0', 'console_scripts', 'reuse')()
  File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.5.0-py3.7.egg/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.5.0-py3.7.egg/reuse/lint.py", line 266, in run
    project = create_project()
  File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.5.0-py3.7.egg/reuse/project.py", line 307, in create_project
    return Project(root)
  File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.5.0-py3.7.egg/reuse/project.py", line 65, in __init__
    self.licenses = self._licenses()
  File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.5.0-py3.7.egg/reuse/project.py", line 287, in _licenses
    "Multiple licenses resolve to {}".format(identifier)
RuntimeError: Multiple licenses resolve to LGPL-2
```

**Comment by carmenbianca** [comment]
Ah, (L)GPL-2.0 is a deprecated licence. I'll create a new issue for that.

**Comment by carmenbianca** [comment]
Ah, #18 is the issue for this.

**Pull request merged**
