### PR TITLE
Add pre-commit hook

### LINKED ISSUE #212: Feature Request: run as pre-commit integration
[pre-commit](https://pre-commit.com/) would be a very good way to make sure that all files (particularly, new files) in the repository are given a license. In particular it would reduce the risk that an explicit `.license` file is created locally (`reuse lint` passes) but not added to the right commit.

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #212.

Great suggestion by @Flameeyes. Implementing this was super easy. This should also be added to the documentation on https://reuse.software/dev/

### CODE REVIEW

**Comment by mxmehl** [comment]
So this is not really the classical pre-commit hook, right?

Normally, it would suffice to create a file in ones `.git/hooks/` directory:

```
#!/bin/sh
reuse lint
```

**Comment by Flameeyes** [comment]
It's the integration for pre-commit.com — which is basically a way to manage "repository side" the configuration of hooks. `pre-commit install` will set up the `.git/hooks/pre-commit` file to run one or more pre-commit checks (and in case, a way to fix them). Tools like black, isort, flake8 and mypy integrate with it as well, so it's easy for a repository to add those without the users needing to do anything but the first install.

**Comment by carmenbianca** [comment]
@mxmehl That would also works, but pre-commit does the following things in addition:

- Automatically downloads the latest stable version of reuse for you
- Installs reuse in a virtual environment for you so you don't need to do anything installation-wise

The advantage of doing that is that the tool handles everything for you without any manual intervention. In turn, that gives you some certainty that all developers use the same pre-commit hook.

As a matter of fact, this repo already used pre-commit with [black](https://github.com/psf/black/) to lint formatting :)

**Comment by mxmehl** [comment]
Thanks for the explanation, sounds interesting and makes a lot of sense :)

**Pull request merged**
