### PR TITLE
Rename --explicit-license to --force-dot-license and improve its help text

### LINKED ISSUE #473: Improve help string of addheader --explicit-license

### PR DESCRIPTION
**Pull request by floriansnow**
Closes #473.

### CODE REVIEW

**Comment by floriansnow** [comment]
Looking at this option, I feel like `--explicit-license` is not a good fit either.  I didn't change it because it's a breaking change and I'm not sure about the process here, but please let me know if I should just add it here or create a separate issue for something like that.

**Comment by carmenbianca** [comment]
If you know a better name, we can change it such that the old name will still work, but only the new name will be presented to the user. Then we just make mention of it in the CHANGELOG

**Comment by floriansnow** [comment]
My suggestions are `--external-license` or `--license-file` or `--external-license-file` in no particular order of preference.

**Comment by carmenbianca** [comment]
What about `--force-dot-license`?

**Comment by floriansnow** [comment]
Sure, I like that too.

**Comment by carmenbianca** [comment]
@floriansnow How do the committed changes look?

**Comment by floriansnow** [comment]
Looks very good to me!  Thank you!

**Comment by mxmehl** [comment]
LGTM, but why not mentioning the deprecated command in the "Deprecated" section of the changelog? ;)

**Review by carmenbianca — APPROVED** [review]

**Review by mxmehl — APPROVED** [review]

**Pull request merged**
