### PR TITLE
Added new copyright style with spdx and string c  as per #948

### LINKED ISSUE #948: Copyright styles and merging
Currently supported styles:

```
    "spdx": "SPDX-FileCopyrightText:",
    "spdx-c": "SPDX-FileCopyrightText: (C)",
    "spdx-symbol": "SPDX-FileCopyrightText: ©",
    "string": "Copyright",
    "string-c": "Copyright (C)",
    "string-symbol": "Copyright ©",
    "symbol": "©",
```

The first issue I encountered is that none of the `_COPYRIGHT_PATTERNS` match the `spdx-c` style, so `--merge-copyrights` is not effective. A small tweak to the first pattern is sufficient - would a PR be accepted?

Secondly, I've been asked to use the (even more redundant) style: "SPDX-FileCopyrightText: Copyright (c) <year>"...
Would a PR to add `sdpx-string-c` (etc.) be accepted?

Thanks!

### PR DESCRIPTION
**Pull request by sin-ha**
Fixes #948

### CODE REVIEW

**Comment by garethsb** [comment]
To fully fix #948, needs to ensure `_COPYRIGHT_PATTERNS` matches all current and added styles.

Although I don't need them, adding `spdx-string` and `spdx-string-symbol`, would make the variations consistent?

**Comment by sin-ha** [comment]
can you please take a look @carmenbianca

**Comment by carmenbianca** [comment]
Hi @sin-ha, I've patched this up. I was reluctant to work on this because it's a bit of a behemoth and #947 is an issue I want to work on to refactor this whole mess.

Incidentally, I integrated #964 en passant. Thank you @sudorook !

**Comment by garethsb** [comment]
@carmenbianca, thanks very much for adding the test cases and docs, agree refactoring per #947 is a good long term plan!

**Pull request merged**
