### PR TITLE
Add support for ".mdlrc", "*.nim.cfg", "*.nimble"

### LINKED ISSUE #365: Recognise `.nimble` and `.nim.cfg` extensions
They both use the same commenting syntax like `.nim`, which is like in python, using `#`.

### PR DESCRIPTION
**Pull request by hoijui**
This fixes #365 and #366.

### CODE REVIEW

**Comment by nicorikken** [comment]
@hoijui Nice! Today I learned bout [Nimble](https://github.com/nim-lang/nimble) and [Markdownlint](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md) 

I like the idea of gradually building the changelog in the PR's, although it might be a source of git conflicts.

Did you forget to add your information in the copyrightheader on the `_comment.py` file?

**Comment by hoijui** [comment]
Added myself there now, thanks!

**Comment by hoijui** [comment]
> @hoijui Nice! Today I learned bout [Nimble](https://github.com/nim-lang/nimble) and [Markdownlint](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md)
> 
> I like the idea of gradually building the changelog in the PR's, although it might be a source of git conflicts.
> 
> Did you forget to add your information in the copyrightheader on the `_comment.py` file?

... are you saying, I should not do it, or split it into separate commits?

**Comment by hoijui** [comment]
Coolest thing would be, when doing a release, to scan all the commit messages since the last release for certain, tagged lines. I bet there is software for that already. that would avoid such conflicts, and still allow to build the change-log gradually, or at least, generate it at any time.
... am not gonna do that. ;-)

**Comment by hoijui** [comment]
I made two separate, smaller, cleaner PRs (#376 & #377), without the CHANGELOG part.
I will keep the CHANGELOG locally though, and might make a separate PR for that, once most of my changes have been merged.

**Comment by nicorikken** [comment]
@hoijui sure, separate PR's are cleaner. It is not my call (I'm not a maintainer) to decide on a strategy, that's why my comment was a bit vague perhaps.

**Comment by mxmehl** [comment]
Thanks for all your changes, @hoijui !

I've also added changelog entries for all your additions :) https://github.com/fsfe/reuse-tool/commit/d09f906896539c0dc4c58bd9c8bc7d1142e5cb3b

**Pull request closed without merging**
