### PR TITLE
Create --skip-existing flag for addheader

### LINKED ISSUE #474: Create reuse addheader --skip-existing
Skip files that already have header information

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #474

### CODE REVIEW

**Comment by mxmehl** [comment]
LGTM. But shall we give some (optional) info message on that this file has been skipped?

**Comment by mxmehl** [comment]
> I think the info message might make sense. But I wouldn't make it optional because that would mean yet another flag, unless we included it in a more general `quiet` flag.

Full ack. I think we already have a --quiet flag for lint. In general, we could think about introducing both quiet and verbose flags for some commands that help debugging or turning down noise for large repos and operations.

For an intermediate solution, what about adding this info message, and dealing with verboseness later?

**Comment by mxmehl** [comment]
Added this info message, very similar to the one from --skip-unrecognised

For me, that would be good to go.

**Comment by carmenbianca** [comment]
Merged manually.

**Pull request closed without merging**
