### PR TITLE
add "spdx-c" --copyright-style option

### PR DESCRIPTION
**Pull request by kbroch-rivosinc**
related to #683

modeled this PR after #350 PR

### CODE REVIEW

**Comment by carmenbianca** [comment]
Per https://github.com/fsfe/reuse-tool/pull/563, `(C)` would probably lead to too many false positives. I'm happy to accept `spdx-c` though.

**Comment by kbroch-rivosinc** [comment]
> Per #563, `(C)` would probably lead to too many false positives. I'm happy to accept `spdx-c` though.

Understood.  I've definitely seen other tools struggle with false positives.

 I'll remove `c` style. Thanks.

**Review by carmenbianca — APPROVED** [review]
LGTM.

Thanks a lot for this contribution! It looks perfect.

**Review by nicorikken — APPROVED** [review]
Thanks!

**Pull request merged**
