### PR TITLE
Fix regression for files without permissions.

### LINKED ISSUE #398: Regression for files without permissions
I noticed an error when testing #347 but didn't think much of it. Turns out the behavior was fine in an earlier version of Reuse, so it is a regression.

### Test setup
Create a script file using super user privileges so it will be owned by root with only read permissions for reuse.
```
$ sudo touch test.sh
$ ls -la
-rw-r--r--  1 root root    0 aug  6 08:13 test.sh
```

### Old behavior
```
$ reuse --version
reuse 0.12.1
```
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021  test.sh
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR] [--style {applescript,aspx,bat,bibtex,c,css,f,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,string,string-c,string-symbol,symbol}] [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line] [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: argument path: can't write to 'test.sh'
```
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021 --explicit-license test.sh
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR] [--style {applescript,aspx,bat,bibtex,c,css,f,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,string,string-c,string-symbol,symbol}] [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line] [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: argument path: can't write to 'test.sh'
```

### New behavior
```
$ git log -n 1
commit d546b1449aea93ac1bffe677e430e1bc004c8435 (HEAD -> master, origin/master, origin/HEAD)
Author: Chris Wesseling <chris.wesseling@cwi.nl>
Date:   Wed Aug 4 18:01:15 2021 +0200

    Allow creating .license file for write-protected files (#347)
```
```
$ reuse --version
reuse 0.13.1.dev19+gd546b14
```
**Here** a regression is introduced as a stacktrace is presented rather than a neat error as shown previously.
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021  test.sh
Traceback (most recent call last):
  File "/home/nico/Software/fsfe/reuse-tool/venv/bin/reuse", line 33, in <module>
    sys.exit(load_entry_point('reuse==0.13.1.dev19+gd546b14', 'console_scripts', 'reuse')())
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/_main.py", line 256, in main
    return parsed_args.func(parsed_args, project, out)
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 605, in run
    result += _add_header_to_file(
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 436, in _add_header_to_file
    with path.open("w", encoding="utf-8", newline=line_ending) as fp:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'test.sh'
```
It doesn't occur when using the `--explicit-license` flag.
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021 --explicit-license test.sh
Successfully changed header of test.sh.license
```
```
$ ls -la
...
-rw-r--r--  1 root root    0 aug  6 08:13 test.sh
-rw-rw-r--  1 nico nico   72 aug  6 08:19 test.sh.license
```

I'm not sure if this is caused by #347 From the code this didn't seem likely. I'll have to take another look at this. Perhaps @CharString you noticed this too?

### PR DESCRIPTION
**Pull request by CharString**
Closes #398

### CODE REVIEW

**Comment by nicorikken** [comment]
Sorry for not looking into this sooner. Thanks for working on this.
I still get the stacktrace output. Am I doing something wrong?
```
$ ls -la tmp/test2.sh 
-rw-r--r-- 1 root root 49 nov  9 10:55 tmp/test2.sh

$ git log -n 1
commit 0e0e4668d14a98f155dc9b1c69e6234c2abb31a3 (HEAD -> issue_398, charstring/issue_398)
Author: Chris Wesseling <Chris.Wesseling@cwi.nl>
Date:   Fri Oct 1 17:04:15 2021 +0200

    Fix linting error and typo.

$ ./venv/bin/reuse --version
reuse 0.13.1.dev33+g0e0e466

$ ./venv/bin/reuse addheader -c 'mycorp' -l Apache-2.0 -y 2020 tmp/test2.sh
Traceback (most recent call last):
  File "./venv/bin/reuse", line 33, in <module>
    sys.exit(load_entry_point('reuse==0.13.1.dev33+g0e0e466', 'console_scripts', 'reuse')())
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/_main.py", line 256, in main
    return parsed_args.func(parsed_args, project, out)
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 605, in run
    result += _add_header_to_file(
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 436, in _add_header_to_file
    with path.open("w", encoding="utf-8", newline=line_ending) as fp:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'tmp/test2.sh'
```

**Comment by mxmehl** [comment]
I cannot reproduce your error, @nicorikken. For me, the following happens which is what I think @CharString intended:

```
$ reuse --version
reuse 0.13.1.dev33+g0e0e466
$ echo foo > bar.md && chmod 444 bar.md
$ ls -l bar.md 
.r--r--r-- 4 max max  9 Nov 16:20 bar.md
$ reuse addheader -c 'mycorp' -l Apache-2.0 -y 2020 bar.md 
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR]
                       [--style {applescript,aspx,bat,bibtex,c,css,f,handlebars,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,spdx-symbol,string,string-c,string-symbol,symbol}]
                       [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line]
                       [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: can't write to 'bar.md'
$ reuse addheader -c 'mycorp' -l Apache-2.0 -y 2020 --explicit-license bar.md
Successfully changed header of bar.md.license
$ cat bar.md.license
SPDX-FileCopyrightText: 2020 mycorp

SPDX-License-Identifier: Apache-2.0
```

Or am I missing something?

**Comment by nicorikken** [comment]
Hmm, I have to do some more debugging in my system them to pinpoint it.

**Comment by nicorikken** [comment]
Perhaps there was some state left from my own Python code. I did a clean clone in a separate directory and now it works:
```
.venv/bin/reuse addheader -c 'mycorp' -l Apache-2.0 -y 2020 tmp/script.sh 
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR]
                       [--style {applescript,aspx,bat,bibtex,c,css,f,handlebars,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,spdx-symbol,string,string-c,string-symbol,symbol}]
                       [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line]
                       [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: can't write to 'tmp/script.sh'
```
Great!!

The code also looks good to me, so Max I approve.

**Comment by CharString** [comment]
@nicorikken No problem

**Comment by mxmehl** [comment]
Yay, happy that it worked out :)

**Pull request merged**
