### PR TITLE
Read default copyright from git/hg configuration

### PR DESCRIPTION
**Pull request by siiptuo**
Use the same configuration files and environment variables as git and hg.

Related to #68

### CODE REVIEW

**Comment by mxmehl** [comment]
Thank you @siiptuo!

@carmenbianca Since you know that I am a terrible code, would you have time to check this PR?

As I get from the code, it reads the author env from the Git config. We would be careful with making this the default though as `author != copyright holder` in some cases, and especially `REUSE user != copyright holder` in many more cases.

**Comment by nicorikken** [comment]
@siiptuo thanks for this contribution. How does this deal with the mis-usage when the variables exist but are empty?

Personally I would like a small log-statement that the environment-variables or git config is used, because this behavior is quite 'magical'. Perhaps something in the debug mode.

I think this is nice for individual copyright owners and contributors.
As @mxmehl mentions, I don't see this work well in a more corporate environment where a company or organization is the copyright holder. Perhaps some additional environment variables could help with that use-case. Then again, one can still write an explicit command, so that can be done at a later stage in a separate issue/PR.

**Comment by siiptuo** [comment]
> How does this deal with the mis-usage when the variables exist but are empty?

This will ignore git/hg config and the user must specify `--copyright`. I think that this unset/override behavior is consistent with  other applications.

> Personally I would like a small log-statement that the environment-variables or git config is used, because this behavior is quite 'magical'. Perhaps something in the debug mode.

Good idea! This is now logged in debug mode.

> We would be careful with making this the default

> I don't see this work well in a more corporate environment where a company or organization is the copyright holder.

I agree that relying on git/hg doesn't work here. But I think that this is a reasonable default if it could be overridden with project-specific `.reuse/config` file as described in #13 and #68. This PR could be the first step in this direction.

**Comment by nicorikken** [comment]
@siiptuo wauw, thanks for your work. For me this seems good to merge. I have yet to try it though, but the code looks correct and is well structured and tested.

**Comment by mxmehl** [comment]
Thanks for the contribution! From what I can see, the code looks fine.

However, I'll have to test this properly first, and also think about possible implications and how to document this to avoid confusion and wrong header entries. I didn't have time to do that yet, so please apologise the delay.

**Comment by mxmehl** [comment]
Sorry for returning to this so late. There have been a number of proposal for sources of information that REUSE shall include, often conflicting, and often causing a problem with various workflows.

Today, 5 of us sat down and tried to find a solution. Please see https://github.com/fsfe/reuse-tool/issues/68#issuecomment-1019229607 for the result.

Unfortunately, that means we won't take info from the Git/Mercurial config, although your code looks great! Instead, we are striving to support a project-wide share config file whose defaults a user can use or ignore.

**Pull request closed without merging**
