### PR TITLE
Add support for the Pijul VCS

### PR DESCRIPTION
**Pull request by korrat**
[Pijul](https://pijul.org) is a new VCS based on a theory of commutative patches. This commit adds support for Pijul to reuse-tool by implementing `VCSStrategyPijul`.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Hi @korrat 

Thanks a heap for this PR! It looks pretty good. I fixed up some things that I swore I would fix whenever the third VCS is added to the tool (to reduce having to write `if` statements everywhere).

Before this can be merged, though, it needs a few things:

- Some tests added
  - This needs a `pijul_repository` fixture in conftest, I think. I'm not sure if it does the rest automagically.
- A change log entry.
- Add yourself to AUTHORS.rst.

Could you take care of these?

**Comment by carmenbianca** [comment]
(Did a sneaky force push to fix a test I caused to fail)

**Comment by korrat** [comment]
I've done, the first three things, and I *think* I also finished step 4, but let's wait on the workflows to confirm.

I've also rebased and force-pushed the branch to solve the conflict with `main`.

**Comment by carmenbianca** [comment]
Awesome work @korrat !

I will review this soon. Thank you so much for your contribution :)

**Comment by korrat** [comment]
I fixed the installation of Pijul and the failing tests. Let me know if you would like me to rebase & squash the fixup commits (or everything).

And thanks a lot for the smooth contribution experience!

**Comment by mxmehl** [comment]
May I add that we also should mention an additional VCS on the website: https://reuse.software/faq/#no-git

VCSs are also mentioned in the README IIRC.

**Review by carmenbianca — APPROVED** [review]
LGTM. I moved the Pijul tests to their own workflow. Thanks a lot for this contribution @korrat

**Comment by korrat** [comment]
Thank you very much for the great experience!

**Pull request merged**
