### PR TITLE
tokenize license to fit 80-char row length

### PR DESCRIPTION
**Pull request by gpongelli**
Downloaded license file have longer row.

With this change the license file will look more familiar .

### CODE REVIEW

**Comment by mxmehl** [comment]
I'm very hesitant towards mangling the license texts we downloaded from SPDX, even if I'd agree that a fixed-width makes them look more familiar.

But that's largely outside the scope of REUSE IMHO.

**Comment by gpongelli** [comment]
Hi @mxmehl , the nltk library is used to truncate text without truncating words .

let me know if there’s interest on this PR and I’ll try to fix the pipeline, otherwise you can close the PR.

thanks.

**Comment by carmenbianca** [comment]
The licences should be used as-is. If you want to wrap the licences, I think it's best to do this manually to make sure the wrapping software made no mistakes.

Even so, I recommend to simply make no changes to the file.

**Comment by gpongelli** [comment]
Hi @carmenbianca , so do you think it's better to change the txt files that will be downloaded (like [this one for MIT](https://raw.githubusercontent.com/spdx/license-list-data/master/text/MIT.txt)) ?

**Comment by carmenbianca** [comment]
That, or don't use `reuse download`, and instead copy the licence text from, say, https://choosealicense.com/licenses/mit/, where it's already wrapped.

**Pull request closed without merging**
