### PR TITLE
Suggest valid SPDX License Identifiers when invalid one is given

### PR DESCRIPTION
**Pull request by siiptuo**
Suggest corrections for typos like "GLP3-or-lter" and unclear licenses like "BSD" in init and download commands.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Hi @siiptuo! Thank you for the pull request.

Unfortunately I won't have time to review it in the coming week/two weeks. After that I'll do my best to review it.

**Comment by carmenbianca** [comment]
I've replaced the jaro dependency with a function from the standard library. I did this because the jaro library is not available in the repositories of some target Linux distributions.

Will do a little more tinkering soon to decouple the logic of generating the error message from the logic of finding similar licenses.

**Comment by carmenbianca** [comment]
Did all the tinkering. Encountered an issue with attempting to download deprecated licenses, though, so will create a separate issue for that.

**Comment by siiptuo** [comment]
Your changes look great! I made a small final fix and rebased everything.

**Comment by carmenbianca** [comment]
Thanks @siiptuo and sorry for the super long wait on this PR

**Pull request merged**
