### PR TITLE
More comment styles defaults.

### PR DESCRIPTION
**Pull request by Flameeyes**
This makes it easier for autotools-based repositories, too.

### CODE REVIEW

**Comment by Flameeyes** [comment]
@carmenbianca fyi :)

**Comment by carmenbianca** [comment]
@Flameeyes Thanks a lot for the PR! I'll look at it more closely very soon. I don't have a lot of time every day to work on this.

At first glance---assuming that all the filetypes are correctly assigned to comment styles---the only additional things that are needed are:

- A line in CHANGELOG
- Your name in the AUTHORS file

:)

**Comment by Flameeyes** [comment]
> @Flameeyes Thanks a lot for the PR! I'll look at it more closely very soon. I don't have a lot of time every day to work on this.

Understood — was just hoping to time it close enough to catch your attention :)

Rebased on top of current master, updated CHANGELOG and AUTHORs.

**Comment by carmenbianca** [comment]
For some reason, I messed something up because the name of the remote branch is `master`. My Git-fy isn't advanced enough to fix it, so I'll open a new PR.

**Pull request closed without merging**
