### PR TITLE
Preserve shebang for more script files

### PR DESCRIPTION
**Pull request by hoijui**
This applies to at least V-Lang scripts.

### CODE REVIEW

**Comment by carmenbianca** [comment]
@mxmehl This needs to be rebased on top of master before it can be merged.

**Comment by carmenbianca** [comment]
@mxmehl Oops, wrong. #477 is not merged yet, but will conflict with this PR.

**Comment by mxmehl** [comment]
Aha, right! Well, shall I push this change to #477 so we don't forget it?

**Comment by mxmehl** [comment]
Rebased on latest master, so good to go!

**Pull request merged**
