### PR TITLE
Improved lint

### PR DESCRIPTION
**Pull request by carmenbianca**
I have very slightly tweaked the output of `reuse lint` to be more concise.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Example output from branch improved-lint-example

```
reuse.project - WARNING - Could not resolve SPDX identifier of LICENSES/another-bad-license.txt, resolving to LicenseRef-Unknown0
MISSING COPYRIGHT OR LICENSING

The following files have no copyright or licensing:
  neither-copyright-nor-licensing
The following files have no copyright:
  bad-license
  missing-license
  only-licensing
The following files have no licensing information:
  only-copyright

BAD LICENSES

'LicenseRef-Unknown0' found in:
  LICENSES/another-bad-license.txt

'bad-license' found in:
  bad-license

MISSING LICENSES

'MIT' found in:
  missing-license

SUMMARY

Bad licenses: LicenseRef-Unknown0, bad-license
Missing licenses: MIT
Unused licenses: LicenseRef-Unknown0, LicenseRef-unused-license
Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later, LicenseRef-Unknown0, LicenseRef-unused-license
Read errors: 0
Files with copyright information: 52 / 56
Files with license information: 54 / 56

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

Still a little strange behaviour in "Used licenses:"

**Comment by carmenbianca** [comment]
Fixed that strange behaviour in be98c6b

**Comment by mxmehl** [comment]
Nice!

Regarding the readability, did you consider applying some Markdown or other markup? Example:

```
# MISSING COPYRIGHT OR LICENSING

The following files have no copyright or licensing:
 * neither-copyright-nor-licensing
The following files have no copyright:
 * bad-license
 * missing-license
 * only-licensing
```

I also thought about putting the different sections in ASCII boxes but perhaps that's overkill

**Comment by carmenbianca** [comment]
Markdownified it like so:

```
reuse.project - WARNING - Could not resolve SPDX identifier of LICENSES/another-bad-license.txt, resolving to LicenseRef-Unknown0
# MISSING COPYRIGHT OR LICENSING

The following files have no copyright and licensing information:
* neither-copyright-nor-licensing

The following files have no copyright:
* bad-license
* missing-license
* only-licensing

The following files have no licensing information:
* only-copyright

# BAD LICENSES

'LicenseRef-Unknown0' found in:
* LICENSES/another-bad-license.txt

'bad-license' found in:
* bad-license

# MISSING LICENSES

'MIT' found in:
* missing-license

# SUMMARY

* Bad licenses: LicenseRef-Unknown0, bad-license
* Missing licenses: MIT
* Unused licenses: LicenseRef-Unknown0, LicenseRef-unused-license
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 52 / 56
* Files with license information: 54 / 56
```

reuse.project - WARNING - Could not resolve SPDX identifier of LICENSES/another-bad-license.txt, resolving to LicenseRef-Unknown0
# MISSING COPYRIGHT OR LICENSING

The following files have no copyright and licensing information:
* neither-copyright-nor-licensing

The following files have no copyright:
* bad-license
* missing-license
* only-licensing

The following files have no licensing information:
* only-copyright

# BAD LICENSES

'LicenseRef-Unknown0' found in:
* LICENSES/another-bad-license.txt

'bad-license' found in:
* bad-license

# MISSING LICENSES

'MIT' found in:
* missing-license

# SUMMARY

* Bad licenses: LicenseRef-Unknown0, bad-license
* Missing licenses: MIT
* Unused licenses: LicenseRef-Unknown0, LicenseRef-unused-license
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 52 / 56
* Files with license information: 54 / 56

**Comment by mxmehl** [comment]
Thanks, much better!

Is the WARNING at the top worth its own section? This way, I am afraid it's easy to be overlooked.

What do you think about adding an extra new line below each completed section?

**Comment by carmenbianca** [comment]
> Is the WARNING at the top worth its own section? This way, I am afraid it's easy to be overlooked.

It's the logger. It's technically part of STDERR, not STDOUT. It is printed out during runtime, rather than as a part of the report at the end. I could change this, but it would be more involved.

Compare for example:

```
reuse._util - DEBUG - running /usr/bin/git status
reuse._util - DEBUG - running /usr/bin/git rev-parse --show-toplevel
reuse._util - DEBUG - running /usr/bin/git status
reuse._util - DEBUG - running /usr/bin/git ls-files --exclude-standard --ignored --others --directory --no-empty-directory -z
reuse.project - DEBUG - determining identifier of LICENSES/CC-BY-SA-4.0.txt
reuse.project - DEBUG - determining identifier of LICENSES/Apache-2.0.txt
reuse.project - DEBUG - determining identifier of LICENSES/CC0-1.0.txt
reuse.project - DEBUG - determining identifier of LICENSES/GPL-3.0-or-later.txt
reuse.project - DEBUG - currently walking in .
reuse.project - DEBUG - ignoring .tox
reuse.project - DEBUG - ignoring .git
reuse.project - DEBUG - ignoring LICENSES
reuse.project - DEBUG - ignoring build
reuse.project - DEBUG - ignoring .vscode
reuse.project - DEBUG - ignoring .reuse
reuse.project - DEBUG - ignoring dist
reuse.project - DEBUG - ignoring .pytest_cache
reuse.project - DEBUG - yielding MANIFEST.in
reuse.project - DEBUG - searching MANIFEST.in for SPDX information
reuse.project - DEBUG - yielding pyproject.toml
reuse.project - DEBUG - searching pyproject.toml for SPDX information
reuse.project - DEBUG - yielding AUTHORS.rst
reuse.project - DEBUG - searching AUTHORS.rst for SPDX information
reuse.project - DEBUG - yielding setup.py
reuse.project - DEBUG - searching setup.py for SPDX information
reuse.project - DEBUG - yielding .pylintrc
reuse.project - DEBUG - searching .pylintrc for SPDX information
reuse.project - DEBUG - yielding CHANGELOG.md
reuse.project - DEBUG - searching CHANGELOG.md for SPDX information
reuse.project - DEBUG - yielding tox.ini
reuse.project - DEBUG - searching tox.ini for SPDX information
reuse.project - DEBUG - yielding .pre-commit-config.yaml
reuse.project - DEBUG - searching .pre-commit-config.yaml for SPDX information
reuse.project - DEBUG - yielding .gitlab-ci.yml
reuse.project - DEBUG - searching .gitlab-ci.yml for SPDX information
reuse.project - DEBUG - yielding requirements.txt
reuse.project - DEBUG - searching requirements.txt for SPDX information
reuse.project - DEBUG - yielding Dockerfile
reuse.project - DEBUG - searching Dockerfile for SPDX information
reuse.project - DEBUG - yielding README.md
reuse.project - DEBUG - searching README.md for SPDX information
reuse.project - DEBUG - yielding Makefile
reuse.project - DEBUG - searching Makefile for SPDX information
reuse.project - DEBUG - ignoring .coverage
reuse.project - DEBUG - yielding .gitignore
reuse.project - DEBUG - searching .gitignore for SPDX information
reuse.project - DEBUG - yielding .editorconfig
reuse.project - DEBUG - searching .editorconfig for SPDX information
reuse.project - DEBUG - yielding .bumpversion.cfg
reuse.project - DEBUG - searching .bumpversion.cfg for SPDX information
reuse.project - INFO - .bumpversion.cfg covered by .reuse/dep5
reuse.project - DEBUG - currently walking in img
reuse.project - DEBUG - currently walking in src
reuse.project - DEBUG - ignoring src/fsfe_reuse.egg-info
reuse.project - DEBUG - currently walking in src/reuse
reuse.project - DEBUG - ignoring src/reuse/__pycache__
reuse.project - DEBUG - yielding src/reuse/download.py
reuse.project - DEBUG - searching src/reuse/download.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/_format.py
reuse.project - DEBUG - searching src/reuse/_format.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/lint.py
reuse.project - DEBUG - searching src/reuse/lint.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/_util.py
reuse.project - DEBUG - searching src/reuse/_util.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/spdx.py
reuse.project - DEBUG - searching src/reuse/spdx.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/__init__.py
reuse.project - DEBUG - searching src/reuse/__init__.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/_licenses.py
reuse.project - DEBUG - searching src/reuse/_licenses.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/project.py
reuse.project - DEBUG - searching src/reuse/project.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/_comment.py
reuse.project - DEBUG - searching src/reuse/_comment.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/report.py
reuse.project - DEBUG - searching src/reuse/report.py for SPDX information
reuse.project - DEBUG - yielding src/reuse/_main.py
reuse.project - DEBUG - searching src/reuse/_main.py for SPDX information
reuse.project - DEBUG - currently walking in src/reuse/resources
reuse.project - DEBUG - yielding src/reuse/resources/exceptions.json
reuse.project - DEBUG - searching src/reuse/resources/exceptions.json.license for SPDX information
reuse.project - DEBUG - ignoring src/reuse/resources/exceptions.json.license
reuse.project - DEBUG - yielding src/reuse/resources/licenses.json
reuse.project - DEBUG - searching src/reuse/resources/licenses.json.license for SPDX information
reuse.project - DEBUG - ignoring src/reuse/resources/licenses.json.license
reuse.project - DEBUG - currently walking in po
reuse.project - DEBUG - yielding po/eo.po
reuse.project - DEBUG - searching po/eo.po for SPDX information
reuse.project - DEBUG - yielding po/nl.po
reuse.project - DEBUG - searching po/nl.po for SPDX information
reuse.project - DEBUG - yielding po/POTFILES.in
reuse.project - DEBUG - searching po/POTFILES.in for SPDX information
reuse.project - DEBUG - yielding po/es.po
reuse.project - DEBUG - searching po/es.po for SPDX information
reuse.project - DEBUG - currently walking in tests
reuse.project - DEBUG - ignoring tests/__pycache__
reuse.project - DEBUG - yielding tests/test_project.py
reuse.project - DEBUG - searching tests/test_project.py for SPDX information
reuse.project - DEBUG - yielding tests/test_report.py
reuse.project - DEBUG - searching tests/test_report.py for SPDX information
reuse.project - DEBUG - yielding tests/test_lint.py
reuse.project - DEBUG - searching tests/test_lint.py for SPDX information
reuse.project - DEBUG - yielding tests/test_util.py
reuse.project - DEBUG - searching tests/test_util.py for SPDX information
reuse.project - DEBUG - yielding tests/test_comment.py
reuse.project - DEBUG - searching tests/test_comment.py for SPDX information
reuse.project - DEBUG - yielding tests/conftest.py
reuse.project - DEBUG - searching tests/conftest.py for SPDX information
reuse.project - DEBUG - yielding tests/test_main.py
reuse.project - DEBUG - searching tests/test_main.py for SPDX information
reuse.project - DEBUG - yielding tests/test_download.py
reuse.project - DEBUG - searching tests/test_download.py for SPDX information
reuse.project - DEBUG - currently walking in tests/resources
reuse.project - DEBUG - yielding tests/resources/fsfe.png
reuse.project - DEBUG - searching tests/resources/fsfe.png for SPDX information
reuse.project - INFO - tests/resources/fsfe.png covered by .reuse/dep5
reuse.project - DEBUG - currently walking in tests/resources/fake_repository
reuse.project - DEBUG - ignoring tests/resources/fake_repository/LICENSES
reuse.project - DEBUG - ignoring tests/resources/fake_repository/.reuse
reuse.project - DEBUG - currently walking in tests/resources/fake_repository/src
reuse.project - DEBUG - yielding tests/resources/fake_repository/src/source_code.c
reuse.project - DEBUG - searching tests/resources/fake_repository/src/source_code.c for SPDX information
reuse.project - INFO - tests/resources/fake_repository/src/source_code.c covered by .reuse/dep5
reuse.project - DEBUG - yielding tests/resources/fake_repository/src/exception.py
reuse.project - DEBUG - searching tests/resources/fake_repository/src/exception.py for SPDX information
reuse.project - INFO - tests/resources/fake_repository/src/exception.py covered by .reuse/dep5
reuse.project - DEBUG - yielding tests/resources/fake_repository/src/source_code.html
reuse.project - DEBUG - searching tests/resources/fake_repository/src/source_code.html for SPDX information
reuse.project - INFO - tests/resources/fake_repository/src/source_code.html covered by .reuse/dep5
reuse.project - DEBUG - yielding tests/resources/fake_repository/src/source_code.py
reuse.project - DEBUG - searching tests/resources/fake_repository/src/source_code.py for SPDX information
reuse.project - INFO - tests/resources/fake_repository/src/source_code.py covered by .reuse/dep5
reuse.project - DEBUG - currently walking in tests/resources/fake_repository/doc
reuse.project - DEBUG - yielding tests/resources/fake_repository/doc/index.rst
reuse.project - DEBUG - searching tests/resources/fake_repository/doc/index.rst for SPDX information
reuse.project - INFO - tests/resources/fake_repository/doc/index.rst covered by .reuse/dep5
reuse.project - DEBUG - currently walking in docs
reuse.project - DEBUG - ignoring docs/_build
reuse.project - DEBUG - yielding docs/authors.rst
reuse.project - DEBUG - searching docs/authors.rst for SPDX information
reuse.project - DEBUG - yielding docs/index.rst
reuse.project - DEBUG - searching docs/index.rst for SPDX information
reuse.project - DEBUG - yielding docs/conf.py
reuse.project - DEBUG - searching docs/conf.py for SPDX information
reuse.project - DEBUG - ignoring docs/readme.md
reuse.project - DEBUG - yielding docs/Makefile
reuse.project - DEBUG - searching docs/Makefile for SPDX information
reuse.project - DEBUG - ignoring docs/history.md
# SUMMARY

* Bad licenses:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 51 / 51
* Files with license information: 51 / 51

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```

> What do you think about adding an extra new line below each completed section?

Sounds like a good idea.

**Comment by carmenbianca** [comment]
Double spacing:

```
reuse.project - WARNING - Could not resolve SPDX identifier of LICENSES/another-bad-license.txt, resolving to LicenseRef-Unknown0
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* neither-copyright-nor-licensing

The following files have no copyright:
* bad-license
* missing-license
* only-licensing

The following files have no licensing information:
* only-copyright


# BAD LICENSES

'LicenseRef-Unknown0' found in:
* LICENSES/another-bad-license.txt

'bad-license' found in:
* bad-license


# MISSING LICENSES

'MIT' found in:
* missing-license


# SUMMARY

* Bad licenses: LicenseRef-Unknown0, bad-license
* Missing licenses: MIT
* Unused licenses: LicenseRef-Unknown0, LicenseRef-unused-license
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 52 / 56
* Files with license information: 54 / 56

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

**Comment by mxmehl** [comment]
> It's the logger. It's technically part of STDERR, not STDOUT. It is printed out during runtime, rather than as a part of the report at the end. I could change this, but it would be more involved.

Ah ok. I have no preference here. If it's irrelevant for the user to accomplish REUSE compliance, I don't care :)

One other find:

> The following files have no copyright:

Let's make it "copyright information" :)

**Comment by carmenbianca** [comment]
> Let's make it "copyright information" :)

Done in 5996928

**Comment by mxmehl** [comment]
LGTM as it is. Thank you :)

**Pull request merged**
