### PR TITLE
Handle deprecated licenses

### LINKED ISSUE #18: Handle deprecated licences and the "+" operator
The tool will currently not recognise `GPL-3.0` or `GPL-3.0+` as a valid licence, preferring instead the new `GPL-3.0-only` and `GPL-3.0-or-later`.

Should the tool consider deprecated licences as valid? Should there be a warning?

The "+" operator remains a part of the SPDX spec, however, and should probably be handled correctly.

### LINKED ISSUE #87: Lint error: Multiple licenses resolve to LGPL-2
I tried to lint the Linux kernel today and received a fatal error, see below:

Git: `git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
Branch: `master`
Commit: `089cf7f6ecb266b6a4164919a2e69bd2f938374a`

This error is rather new, with 0.4.0, linting Linux didn't throw an error.

```
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/Apache-2.0, resolving to Apache-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/CDDL-1.0, resolving to CDDL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/MPL-1.1, resolving to MPL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/exceptions/GCC-exception-2.0, resolving to GCC-exception-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/GPL-2.0, resolving to GPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.0, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.1, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - CRITICAL - LGPL-2 is the SPDX License Identifier of both LICENSES/preferred/LGPL-2.1 and LICENSES/preferred/LGPL-2.0
Traceback (most recent call last):
  File "/usr/bin/reuse", line 11, in <module>
    load_entry_point('fsfe-reuse==0.5.0', 'console_scripts', 'reuse')()
  File "/usr/lib/python3.7/site-packages/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/usr/lib/python3.7/site-packages/reuse/lint.py", line 255, in run
    project = create_project()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 297, in create_project
    return Project(root)
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 63, in __init__
    self.licenses = self._licenses()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 277, in _licenses
    "Multiple licenses resolve to {}".format(identifier)
RuntimeError: Multiple licenses resolve to LGPL-2
```

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #18 

Kind of. It only deals with deprecated licenses, not with the "+" operator.

Together with #89 this is necessary to fix #87 

Not *entirely* happy with this patch, though. The clunkiness of `lint.py` is starting to show. I'm really happy with `report.py` though.

One remark while writing this patch: The order of the items in the `lint` summary is NOT consistent inside of the codebase. It would be nice if this were fixed?

### CODE REVIEW

**Comment by carmenbianca** [comment]
@mxmehl If I merge with master, I get this output on the Linux kernel:

```
# SUMMARY

* Bad licenses:
* Deprecated licenses: GPL-1.0, GPL-2.0
* Licenses without file extension: Apache-2.0, BSD-2-Clause, BSD-3-Clause, BSD-3-Clause-Clear, CDDL-1.0, GCC-exception-2.0, GPL-1.0, GPL-2.0, ISC, Linux-OpenIB, Linux-syscall-note, MIT, MPL-1.1, X11
* Missing licenses: GPL-1.0+, GPL-2.0+, GPL-2.0-only, GPL-2.0-or-later, LGPL-2.0+, LGPL-2.1, LGPL-2.1+
* Unused licenses: BSD-3-Clause-Clear, GPL-1.0
* Used licenses: Apache-2.0, BSD-2-Clause, BSD-3-Clause, CDDL-1.0, GCC-exception-2.0, GPL-2.0, ISC, Linux-OpenIB, Linux-syscall-note, MIT, MPL-1.1, X11
* Read errors: 0
* Files with copyright information: 38770 / 65221
* Files with license information: 46375 / 65221

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

Some notes:

- It would probably be nice to somehow automagically deal with the `+` and `-or-later` thingamajigs.
- The Linux kernel flat-out simply doesn't provide some license files (the LGPLs).
- Not all files are covered still.

**Comment by carmenbianca** [comment]
Oh, oops, my fault. I somehow for some reason removed the LGPL licenses in my HEAD. They are totally there.

**Comment by carmenbianca** [comment]
Actual output on a more recent kernel commit:

```
# SUMMARY

* Bad licenses:
* Deprecated licenses: GPL-1.0, GPL-2.0, LGPL-2.0, LGPL-2.1
* Licenses without file extension: Apache-2.0, BSD-2-Clause, BSD-3-Clause, BSD-3-Clause-Clear, CDDL-1.0, GCC-exception-2.0, GPL-1.0, GPL-2.0, ISC, LGPL-2.0, LGPL-2.1, Linux-OpenIB, Linux-syscall-note, MIT, MPL-1.1, X11
* Missing licenses: GPL-1.0+, GPL-2.0+, GPL-2.0-only, GPL-2.0-or-later, LGPL-2.0+, LGPL-2.1+
* Unused licenses: BSD-3-Clause-Clear, GPL-1.0, LGPL-2.0
* Used licenses: Apache-2.0, BSD-2-Clause, BSD-3-Clause, CDDL-1.0, GCC-exception-2.0, GPL-2.0, ISC, LGPL-2.1, Linux-OpenIB, Linux-syscall-note, MIT, MPL-1.1, X11
* Read errors: 0
* Files with copyright information: 38984 / 65662
* Files with license information: 47008 / 65662

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

**Comment by mxmehl** [comment]
Thanks!

> It would probably be nice to somehow automagically deal with the + and -or-later thingamajigs.

You mean somehow marking them in the "Missing" section as deprecated? 

Linux indeed has a strange setup by including the license text as `GPL-2.0`, but referring to it as GPL-2.0, GPL-2.0+, GPL-2.0-or-later and such. Not sure whether we will be able to cover all of these...

**Comment by carmenbianca** [comment]
> You mean somehow marking them in the "Missing" section as deprecated?

I meant that if `GPL-2.0` is found in `LICENSES/`, and `GPL-2.0+` is later found in a comment header, then `GPL-2.0+` *probably* shouldn't be marked as missing.

There's a lot of magic involved there, though. I'm a little bit apprehensive about undertaking that right now, so I've created issue #123.

**Pull request merged**
