### PR TITLE
Add support for PHP header

### LINKED ISSUE #436: `reuse addHeader` broken for PHP
When calling `reuse addheader` on PHP files the comment header is placed _outside_ the `<?php` tag, which is incorrect.

To demonstrate, assume we have an example file with this content:
```php
<?php

// some code here
```

Then this happens:

## Multiline Comment

<table>
<tr><td>Command</d><td>

`reuse addheader --license="MIT" ./example.php --multi-line`

</d></tr>
<tr><td>Expected</d><td>

  ```php
  <?php

  /*
   * SPDX-License-Identifier: MIT
   */
  ```

</d></tr>
<tr><td>Actual</d><td>

  ```php
   /*
    * SPDX-License-Identifier: MIT
    */

   <?php
   ```

</d></tr>
</table>

## Single line Comment

<table>
<tr><td>Command</d><td>

`reuse addheader --license="MIT" ./example.php`

</d></tr>
<tr><td>Expected</d><td>

 ```php
 <?php

// SPDX-License-Identifier: MIT
 ```

</d></tr>
<tr><td>Actual</d><td>

```php
// SPDX-License-Identifier: MIT

 <?php
 ```

</d></tr>
</table>

### LINKED ISSUE #537: PHP comment style edge-case for functions.php in WordPress theme
I just applied `reuse addheader` on a WordPress theme generated using the [new-empty-theme.php](https://github.com/WordPress/theme-experiments/blob/master/new-empty-theme.php). In the `functions.php` file the resulting start of the document is as below:

```php
// SPDX-FileCopyrightText: 2019-2022 WordPress Theme Experiments contributors
//
// SPDX-License-Identifier: GPL-2.0-or-later

<?php

if ( ! function_exists( 'my_theme_support' ) ) :
	function my_theme_support()  {
```

But in the WordPress (version 6.0) UI now this comment leaks into the UI:

afbeelding

I'm not sure if this is a WordPress issue or a REUSE issue, I have yet to look into it in greater detail. But I thought I'd better make it explicit in case others encounter the same issue in the future.

My guess is that it fails because the comment is placed before the `<?php` tag and so this content directly ends up in the HTML.

### PR DESCRIPTION
**Pull request by yamanq**
closes #436
closes #537

### CODE REVIEW

**Comment by nicorikken** [comment]
Thanks @yamanq I tested it and it works. Can you add your copyright annotation to the file and add yourself to the https://github.com/fsfe/reuse-tool/blob/master/AUTHORS.rst to claim your credits?

**Comment by yamanq** [comment]
Rebased and added, thanks for taking a look.

**Comment by jtojnar** [comment]
By copyright annotation, they probably meant https://github.com/yamanq/reuse-tool/blob/php/src/reuse/header.py#L1-L9.

**Comment by yamanq** [comment]
Oh you're right. I added that too.

**Comment by nicorikken** [comment]
Thanks @jtojnar for stepping in. Indeed it was about both. Thanks @yamanq , looks good to merge for me. I'll approve it and see if I can get another review of it.

**Review by nicorikken — APPROVED** [review]

**Pull request merged**
